sudo: required
matrix:
  include:
    - os: osx
      language: generic # OS X comes with Python 2 installed
    - language: python
      python: "2.7"
install:
  - sudo ./install.sh
  - source ~/.profile
  - pip install pydub # this installs inside virtualenv
script:
  - python test/test.py