sudo: required
matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      python: 2.7
install:
  - ./install.sh
  - source ~/.profile
  - python -m pip install pydub
script:
  - python test/test.py
