sudo: required

services:
  - docker

matrix:
  include:
  - install:
    - find test/audio -type f ! -iname "SBC018.wav" -delete
    - find test/transcripts -type f ! -iname "SBC018.trn" -delete
  - install:
    - find test/audio -type f ! -iname "SBC010.wav" -delete
    - find test/transcripts -type f ! -iname "SBC010.trn" -delete
  - install:
    - find test/audio -type f ! -iname "SBC022.wav" -delete
    - find test/transcripts -type f ! -iname "SBC022.trn" -delete
  - install:
    - find test/audio -type f ! -iname "lucier.mp3" -delete
    - find test/transcripts -type f ! -iname "lucier.trn" -delete

script:
  - travis_wait 45 docker run -v "$(pwd)":/canetis nsheth12/canetis-base python -u test/test.py
