sudo: required

services:
  - docker

env:
  - FILE=lucier MODE=gentle
  - FILE=lucier MODE=canetis
  - FILE=SBC018 MODE=gentle
  - FILE=SBC018 MODE=canetis
  - FILE=SBC010 MODE=gentle
  - FILE=SBC010 MODE=canetis
  - FILE=SBC022 MODE=gentle
  - FILE=SBC022 MODE=canetis
  - FILE=SBC027 MODE=gentle
  - FILE=SBC027 MODE=canetis
  - FILE=SBC033 MODE=gentle
  - FILE=SBC033 MODE=canetis
  - FILE=SBC040 MODE=gentle
  - FILE=SBC040 MODE=canetis
  - FILE=SBC046 MODE=gentle
  - FILE=SBC046 MODE=canetis
  - FILE=SBC047 MODE=gentle
  - FILE=SBC047 MODE=canetis
  - FILE=SBC048 MODE=gentle
  - FILE=SBC048 MODE=canetis
  - FILE=SBC050 MODE=gentle
  - FILE=SBC050 MODE=canetis

install:
  - docker pull nsheth12/canetis-base
  - find test/audio -type f ! -iname "$FILE*" -delete && find test/transcripts -type f ! -iname "$FILE*" -delete

script:
  - travis_wait 50 docker run -e MODE -v "$(pwd)":/canetis nsheth12/canetis-base time python -u test/test.py
