sudo: required
language: python
python:
  - "2.7"
install:
  - sudo ./install.sh
  - source ~/.profile
  - pip install pydub # this installs inside virtualenv
script:
  - travis_wait 40 python test/test.py