sudo: required
matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      python: 2.7
install:
  - ./install.sh
  - source ~/.profile
  - pip install pydub || pip2 install pydub # this installs inside virtualenv
script:
  - python test/test.py