sudo: required
matrix:
  include:
    - os: osx
      language: generic
      before_install:
        - brew install python
    - language: python
      python: "2.7"
install:
  - sudo ./install.sh
  - source ~/.profile
  - pip install pydub # this installs inside virtualenv
script:
  - python test/test.py