sudo: required
matrix:
  include:
    - os: osx
      language: generic
      before_install:
        # upgrade pip to deal with python.org TLS issue
        - curl https://bootstrap.pypa.io/get-pip.py | python
        - pip install --upgrade setuptools
    - os: linux
      language: python
      python: 2.7
install:
  - ./install.sh
  - source ~/.profile
  - python -m pip install pydub
script:
  - python test/test.py
